### ISSUE TITLE
Minor tweaks and cleanup tasks

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#108]
- reduce 3BLD auto-blacklist thresholds to 14.5s and 18s single/mean
- add blurb to Dino Cube event description saying that any solved state is solved
- add blurb to FMC event description mentioning that rotations are not counted as a move

**Comment by marceloFA** [comment]
@euphwes, how do I run a new revision (migration)? I tried ``alembic revision -m "Update dino cube event description"`` but then I get `` FAILED: No 'script_location' key found in configuration.``.
I think it may be because at ``alembic.ini`` there should be a ``script_location = .`` under the ``[alembic]`` session? Even if I add this, I get an error, but this time the error is: 
``` 
  File "/home/marcelo/cubers.io/migrations/versions/001_011ec2822d26.py", line 10, in <module>
    from app.persistence.models import EventFormat
ModuleNotFoundError: No module named 'app'
```
Can you help on this one, please? 😂

**Comment by marceloFA** [comment]
After a read on [this discussion](https://stackoverflow.com/questions/33821470/importing-app-when-using-alembic-raises-importerror) a short-term fix for the error I mentioned above is to temporarily add the current folder to the interpreter path like this: ``PYTHONPATH=.`` in addition to mentioning the ``script_location=migrations`` at ``migrations/alembic.ini``.

Now from the project root, I can create new revisions running 
``PYTHONPATH=. alembic -c migrations/alembic.ini revision -m "blablabla"``

**Comment by euphwes** [comment]
Hey, sorry I missed this! Looks like you had it worked out. I typically create new DB revisions like this:

`flask db migrate -m "migration info"`

and it's just worked for me. No need to temporarily tweak the python path or anything.

**Comment by euphwes** [comment]
Resolved in @marceloFA 's merged PR from a few days ago.
