### ISSUE TITLE
FTO - Face Turning Octahedron!

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#147]
Let's add Face Turning Octahedron as a new event.

- [x] Ao5
- [x] Weekly event
- [x] Random moves scrambler with 30 moves (see notes from Edd below)
- [x] Scramble preview
    - [x] Shape/layout
    - [x] Color scheme
    - [x] Apply scramble
- [x] Custom color options

Thanks /u/g253 for the idea!

**Comment by EddtheRexMan** [comment]
Hello my name is Edd, I'm new to github but also I am currently ranked #1 in Europe and #8ish in the world on the [FTO rankings](https://docs.google.com/spreadsheets/d/1Pr7vqSdNtTaGYwQzQMFEQ_NqujVAcZSn8E4ccpOGfJY/edit?fbclid=IwAR3KZ_4qZ2MPCk23HyRmVVahI3GzoS96F42fYkQveyZSWqkr7QwRUl14cXE#gid=1091974906)!

We currently don't have a random-state scrambler, so we use a random move scramble of 30 moves. Someone did the maths and found that 25 moves is too few to reach the state space or something (I don't fully understand it, sorry).

I believe SixStringCal made [software](https://github.com/Sixstringcal/FTODrawer?fbclid=IwAR2j3uJFB6NrMrGgdcyWd7lZU2fhrlIKiIWKTdQp6JUgrdhhc4DsH8RQ7qo#readme) that can generate a scramble preview and its colours can be customised.

A lot of people have different colour schemes but the most common are the stock LanLan colours and also Ben's first colour scheme, which is in his [tutorial document](https://docs.google.com/document/d/e/2PACX-1vTDL7-XvpNrhIc2Q_1nHfeJyG7tIazgBCq88PE8ahqIbvPb3LPQsM3_vsdqX6y8sxte1n5jGk2J3c5V/pub). 

All competitions for FTO have used Ao5 format because you can expect times from about 30s to 2 minutes, with the fastest times approaching low20s. 

I would love to see FTO added with 30 move scrambles in an Ao5 format, and I think the FTO community would agree.

Cheers,
Edd

**Comment by euphwes** [comment]
That's all great info, thanks @EddtheRexMan ! It should be straightforward enough to add in that 30-move random moves scrambler. I'll use that scramble preview software you linked as a reference; I won't be able to use those images directly in cubers.io, since they're drawn on the fly in canvas on the page (rather than pre-rendered), but having a reference will still be great help.

I'll probably use the LanLan scheme as the default FTO color scheme, and will make the colors configurable.

Ao5 works for me! Thanks again. I'll get to work on this ASAP and hopefully will have it running in our weekly comps in a couple weeks!

**Comment by euphwes** [comment]
![image](https://user-images.githubusercontent.com/5588930/101421185-ffaf2500-38b0-11eb-8452-d615128985f6.png)

![image](https://user-images.githubusercontent.com/5588930/101421202-09d12380-38b1-11eb-90dc-4a1ec463f2df.png)

![image](https://user-images.githubusercontent.com/5588930/101421211-0fc70480-38b1-11eb-88a5-14cc9524b026.png)

![image](https://user-images.githubusercontent.com/5588930/101421310-40a73980-38b1-11eb-8936-a259e9f73344.png)

![image](https://user-images.githubusercontent.com/5588930/101421325-469d1a80-38b1-11eb-846c-cdbdce273c58.png)

**Comment by euphwes** [comment]
![image](https://user-images.githubusercontent.com/5588930/102116782-b142de80-3dfa-11eb-9bef-810fd153663b.png)
