### ISSUE TITLE
Improve manual time entry

### ISSUE THREAD

**Issue by topppits** [euphwes/cubers.io#16]
Right now the manual time entry is more time consuming than I'd love it to be. 
1. click on time
2. click on "Manual time entry"
3. enter time including : and .
4. click on Ok with mouse or press tab twice and hit enter with keyboard (just hitting enter after entering the time does nothing :()

This includes switching between mouse and keyboard and a couple more steps than needed imo. I typically time my solves in my main timer and then input them into cubers.io, since I also want those solves in my main timer, but I started doing it mainly, since there's no inspection time (yet) on cubers.io. So ideally I'd finish the solve, press alt+tab to switch to the cubers.io tab, input time, press enter, alt+tab back to my main timer.

Inputting : and . is pretty annoying. It would be nice to have 12345 recognized as 1:23.45.

Also an additional option to switch to manual input in general / for the average you're doing at the moment.

You could have an option on the user settings page if someone wants to use manual time entry as their standard and then a toggle button on the page where you are actually doing an event.

In "manual time entry"-mode just have a text field instead of the time or sth like that and with enter and/or a button you can confirm the time. Automatic focus on the text field after confirming a time, so I don't have to switch to my mouse again and click into the field. Also don't lose focus if I switch to another window and then come back to this - not sure if this could be an issue.
Automatically adding the : and . would be a plus or just recognising 12345 as 1:23.45 as suggested above.

**Comment by euphwes** [comment]
I see some ambiguity in something like "123" - does this mean 1.23, or 1:23 (aka 1:23.00)? I assume the latter, but can we assume that everybody would input the time the same way? I can see there being some confusion around that point.

If we assume that the user always enters times with the centiseconds, I guess there's no problem there. This should be the case, given that any cube timer will give you the centiseconds, but what about stackmat? Times there give you thousands of a second: 12.345 for 12.34 seconds.

Somebody just transcribing from their stackmat to cubers.io might just mindlessly copy '12345' over and suddenly their time becomes 1:23.45 instead of 12.34.

In general this is probably not a huge concern, it's not like somebody wouldn't notice their time got interpreted differently than expected, and they would have the option to fix it.

Let me think on it a bit. I might close this and re-open as a couple separate issues, since they are logically separate tasks.

- additional time interpretation logic (ex. 12345 without decimals or colons interpreted as 1:23.45)
- some sort of in-page toggle to switch to manual time entry mode, where text boxes are available for time entry
- user option for defaulting to manual time entry over using the timer

Thanks!

**Comment by topppits** [comment]
>manual time entry mode, where text boxes are available for time entry

For this mode you could just change the timer to a textbox.

To make typing in the times easier and rule out ambiguity you could add the . and : automatically.
Let's say you'd want to add the time 12.345:
After typing the first digit you'd see 0.01, then 0.12, then 1.23 and then 12.34. That should make it already pretty clear, that we only use 2 decimals, but if somone keeps typing they'd get 1:23.45 and that should make it absolutely clear. Deleting the last one should get the time back to 12.34.

**Comment by euphwes** [comment]
Closing this, as the work is in-progress (nearly done) as part of the timer page overhaul from issue #65.
