### ISSUE TITLE
3BLD gives you the "finished" message after every solve

### ISSUE THREAD

**Issue by topppits** [euphwes/cubers.io#20]
and to get the next scramble you have to go back and click on 3BLD again.

![3bld weekly comp](https://user-images.githubusercontent.com/45535675/51549887-80a2d600-1e6b-11e9-961e-33e06da7bc1d.PNG)

**Comment by euphwes** [comment]
Ah, after tweaking some logic to make it possible to display PB singles and averages above, basically there are conflicting events:
- Is this event done? If yes, show the results (blind events are considered done after 1 solve because it's based on best single, not average)
- Is there still a scramble left to show? If yes, show it and prepare to save results for that scramble

The first one wins because it happens last. I'll get a fix out soon. Thanks!
