### ISSUE TITLE
Request: Addition of BiCube (Bandaged Cube) as event

### ISSUE THREAD

**Issue by JackTriton** [euphwes/cubers.io#218]
Hi! Former UWR single, ao5, current ao12 holder of BiCube here.
Adding BiCube (Bandaged Cube, Meffert's Bandaged Cube) as an event (or bonus event) would be great since there are some rises on solving it.

The scramble of it can be generated using cstimer so that's not the problem.
The hardest part is to draw the scramble since the parts are bandaged (The solution for this would be create the list of bandaged state, get how the pieces are connected and join them. or store all of the piece shape and place each one of them).

**Comment by euphwes** [comment]
Hey @JackTriton ! Thanks for the request. This actually sounds like a lot of fun from a development point of view. That's great to know that a scrambler is available in csTimer. I think the scramble drawing won't be too much of a challenge, I have a few thoughts about how it can be implemented pretty cleanly.

Making this a rotating bonus event makes the most sense to me; I imagine the participation rate will be pretty low, like it already is with the other niche bonus events.

To be clear, this is the specific bandaged cube configuration that you're referring to, right?

![Screenshot 2024-04-16 at 11 02 19 AM](https://github.com/euphwes/cubers.io/assets/5588930/67a993ea-b5a7-4191-9ccf-7d1046c92168)

I can't promise any particular timeline for getting this into cubers.io, since real life is busy for me lately, but I *have* been itching for a smaller project to implement within cubers.io and this seems like a great option.

**Comment by euphwes** [comment]
Note for myself, playing around with my own BiCube and the cstimer scrambler: scramble orientation appears to be orange top, yellow front, with orange/yellow/green corner at UFR.

**Comment by euphwes** [comment]
Oh I creeped around on the speedsolving wiki and found your [UWR video](https://www.speedsolving.com/wiki/index.php/List_of_Unofficial_World_Records) -- it looks like your cube has the color scheme swapped so the single 1x1x1 corner is actually white/green/red, and you scramble with the usual white top, green front.

I found this other net image of the design 

![Screenshot 2024-04-16 at 11 53 26 AM](https://github.com/euphwes/cubers.io/assets/5588930/352d9d50-b1be-4957-8328-f4b735ba831c)

I'll probably just implement it so that the scramble-able orientation is white top, green front like other puzzles.

**Comment by euphwes** [comment]
![bicube_eventcard](https://github.com/euphwes/cubers.io/assets/5588930/10ccdd66-9417-4936-86f4-e0985b2c20ba)

**Comment by euphwes** [comment]
Slightly different styling of the scramble preview:

![bicube alternative](https://github.com/euphwes/cubers.io/assets/5588930/7fbcc037-2ba7-4bad-b10b-1110f9eaba14)

vs

![bicube_scramble1](https://github.com/euphwes/cubers.io/assets/5588930/7ac77d62-3e44-4c06-8e7d-85fb2a9edd5f)

I think I'm leaning towards the first one above, it looks more natural with a black background and less rounding on the stickers' corners.

**Comment by JackTriton** [comment]
> ![bicube_eventcard](https://github.com/euphwes/cubers.io/assets/5588930/10ccdd66-9417-4936-86f4-e0985b2c20ba)
> 
> 

Great design!
But I think for the icon, rotate it 90 degrees anti-clockwise would be better

**Comment by euphwes** [comment]
![eventcard_p2](https://github.com/euphwes/cubers.io/assets/5588930/59c715cd-a903-4f49-a5de-6ede0bd73c34)

Looks good to me either way. I modeled it after the U face, but F face looks nice too. cc @JackTriton

**Comment by euphwes** [comment]
Now I need to learn how to solve the BiCube, so I can participate in this when it rolls around every few weeks or so :-) I'll probably ship it this weekend, but I don't know offhand if it'll fall into next week's bonus event rotation or a following one.

**Comment by JackTriton** [comment]
> Now I need to learn how to solve the BiCube, so I can participate in this when it rolls around every few weeks or so :-) I'll probably ship it this weekend, but I don't know offhand if it'll fall into next week's bonus event rotation or a following one.

These two would help you to learn it!
[JAAP Bicube](https://www.speedsolving.com/threads/triton-method-my-own-bandaged-cube-bicube-speed-solving-method.86035/)
[Triton Method](https://www.speedsolving.com/threads/triton-method-my-own-bandaged-cube-bicube-speed-solving-method.86035/)

**Comment by euphwes** [comment]
@JackTriton This is live and working well! I put BiCube in the bonus event rotation, and it'll show up every few weeks. The first time it shows up will be in next week's competition :-) Thanks again for the fun suggestion! And thanks for the links, I'll see if I can't learn BiCube sooner or later.
