### ISSUE TITLE
Averages not rounding properly

### ISSUE THREAD

**Issue by turnthispage** [euphwes/cubers.io#49]
I noticed for my average in Mar 2019 Week 2, the mean of my counting solves was 28.10666... but the average was listed as 28.10 instead of 28.11.

**Comment by euphwes** [comment]
Thanks for pointing this out! I initially thought averages were also subject to the truncation rule (12.139 and 12.341 both get recorded as 12.34 for individual solves, for example), but turns out that's just for single solves.

Means/averages do get rounded: https://www.worldcubeassociation.org/regulations/#9f1

I'll get a fix in ASAP. Unfortunately it won't be feasible to fix old results, but since it's a relatively minor issue, I think it's ok to have properly-rounded results going forward.

Thanks for bringing it to my attention!
