### ISSUE TITLE
Making results easier to read

### ISSUE THREAD

**Issue by turnthispage** [euphwes/cubers.io#51]
Right now if you're looking at the leaderboard you see from left to right the average, the single, and then the five solves of the average. I've been finding it a little difficult to read because the spacing between the single and the rest of the solves seems to be the same, whereas I think the average is a little further away and it is also bolded which makes it stand out more. I'm not sure if both the single and the average should be bolded and the spacing should stay the same, or if the spacing should change as well, or if the single shouldn't be bolded but the spacing should change. The same issue also applies to looking at someone's results on their profile, but there nothing is bolded. Sorry if that's tough to understand, it's hard to describe in writing.

**Comment by euphwes** [comment]
I've visually separated the individual solves from the average/single results, in both the leaderboards tables and the user profile pages, which I think should help make it easier to read.

You mentioned that either the average or the single is bolded... In the leaderboards tables, the bold result indicate what that event is ranked by. For example, 3x3 is ranked by average, so averages are bold, but 3BLD is ranked by best single, so single is bold there.

Only a little over a year after you opened the issue here, did I finally address it, lol. Thanks for your patience :-)
