### ISSUE TITLE
Some site ranks don't show on user profile

### ISSUE THREAD

**Issue by CMOSSystem** [euphwes/cubers.io#89]
![image](https://user-images.githubusercontent.com/35967119/61772909-a77a9e80-adf3-11e9-9002-a74d8d9166d3.png)

Above image is a part of my profile (https://www.cubers.io/u/CMOS_System/), and the site rank is not displayed for the first three events even though I have a time that should be associated with a rank. This also happens to other profiles, but it's not always the same events.

**Comment by euphwes** [comment]
Thanks for the report! The bug was related to the changes I made recently for tie-breaking, and displaying tied rankings. You happened to be tied with other users for your 2x2, 3x3, 3x3OH average ranks.

Got it fixed, and re-ran site rankings as of last week's competition, so your profile (and the other affected ones) are showing ranks correctly now.
