### ISSUE TITLE
Site ranks become inaccurate when there are users whose ranks have not been calculated yet

### ISSUE THREAD

**Issue by bryankroesbeek** [euphwes/cubers.io#99]
These do correctly show (I think) on the records page, but when you go to a user's profile their rank is inaccurate.

![image](https://user-images.githubusercontent.com/16594529/63924845-504a9800-ca49-11e9-8b28-90785648e1b9.png)
in this image we see that lurigrang has a site rank of 35 yet if we go to the profile page:
![image](https://user-images.githubusercontent.com/16594529/63924553-c0a4e980-ca48-11e9-9d5d-9f2a9e147fa2.png)
We can see that it says that the rank is 34, which is not correct.

If we then look at the profile that should be on rank 34:
![image](https://user-images.githubusercontent.com/16594529/63924612-d74b4080-ca48-11e9-8973-ca2f760087fe.png)
We can see that the records data is not yet calculated. which causes this inaccuracy.

This becomes more extreme when we select a user further down in the rankings

**Comment by euphwes** [comment]
We discussed in the developer chat -- this is intentional, because it's too slow and computationally expensive to do it live on each profile page load. Instead, we calculate user site rankings once per week (usually) at the end of each competition, and store that information as a static thing that's quick to retrieve and parse through to get the user's specific information.
